apiVersion: v1
kind: Namespace
metadata:
    name: waveapp-namespace
spec:
    finalizers:
      - kubernetes


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-data-pv
  labels:
    type: local
spec:
  storageClassName: sonaqrube-data
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"



---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-extentions-pv
  labels:
    type: local
spec:
  storageClassName: sonarqube-extentions
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"


---
# Persistent volume claim to remember Sonarqube setup
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-data-pvc
spec:
  storageClassName: sonaqrube-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-extentions-pvc
spec:
  storageClassName: sonarqube-extentions
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec: 
      containers:
        - name: h2o-wave-container
          # change this to 'borisdundakovwebapp.azurecr.io/h2o-wave-app:v2' if undesired result
          image: borisdundakovwebapp.azurecr.io/h2o-wave-app:v3
          ports:
            - containerPort: 10101
          command:
            - /bin/bash
            - -c
            - |
              cd ai_app/
              wave run app.py

        
        
        - name: sonarqube-container # this is where the analysis made by sonaqrube will be viewed
          image: borisdundakovwebapp.azurecr.io/sonarqube-with-prometheus:v1
          ports:
            - containerPort: 9000
          
          # Here is where the issue lies!
          # volumeMounts:
          #   - name: sonarqube-data
          #     mountPath: /opt/sonarqube/data
          #   - name: sonarqube-extentions
          #     mountPath: /opt/sonarqube/extentions
      
      volumes:
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: sonarqube-data-pvc
        - name: sonarqube-extentions
          persistentVolumeClaim:
            claimName: sonarqube-extentions-pvc
  
---

apiVersion: v1
kind: Service
metadata:
  name: port-balancer
spec:
  type: LoadBalancer # Exposes public IP of the application
  ports:
    - name: h2o-wave-port
      port: 10101
      targetPort: 10101
    - name: sonarqube-port
      port: 9000
      targetPort: 9000
  selector:
    app: my-app