apiVersion: v1
kind: Namespace
metadata:
    name: waveapp-namespace
spec:
    finalizers:
      - kubernetes

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec: 
      containers:
        - name: h2o-wave-container
          # change this to 'borisdundakovwebapp.azurecr.io/h2o-wave-app:v3' if undesired result
          image: borisdundakovwebapp.azurecr.io/h2o-wave-app_prod:v.1.0.3
          ports:
            - containerPort: 10101
          command:
            - /bin/bash
            - -c
            - |
              cd ai_app/
              wave run app.py
      
        - name: sonarqube-container # this is where the analysis made by sonaqrube will be viewed
          image: borisdundakovwebapp.azurecr.io/sonarqube-with-prometheus_prod:v.1.0.0
          ports:
            - containerPort: 9000
  
---

apiVersion: v1
kind: Service
metadata:
  name: port-balancer
spec:
  type: LoadBalancer # Exposes public IP of the application
  ports:
    - name: h2o-wave-port
      port: 10101
      targetPort: 10101
    - name: sonarqube-port
      port: 9000
      targetPort: 9000
  selector:
    app: my-app