apiVersion: v1
kind: Namespace
metadata:
    name: waveapp-namespace
spec:
    finalizers:
      - kubernetes


#Prometheus setup
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  AZURE_STORAGE_ACCOUNT: Y3NhMTAwMzIwMDI4NzMwZGZjMQ==
  AZURE_STORAGE_ACCESS_KEY: Zl0JHyX49sWFjgz+rYepRgaAui6sv0qDwR0c4nOwXWWBWCQ3L+cF2ivzsSpwgMmB58b4PyQ/gJr5+ASteR5//Q==

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  storageClassName: prometheus-storage-class
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  azureFile:
    secretName: azure-secret
    shareName: prometheus
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: prometheus-storage-class
  volumeName: prometheus-pv

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 30s
    scrape_configs:
      - job_name: 'azure-vm'
        static_configs:
        - targets: ['20.107.212.190:9100'] 
---
# localhost 9100 is where node exporter stats are

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-extentions-pv
  labels:
    type: local
spec:
  storageClassName: sonarqube-extentions
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-data-pv
  labels:
    type: local
spec:
  storageClassName: sonarqube-data
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
# Persistent volume claim to remember Sonarqube setup
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-data-pvc
spec:
  storageClassName: sonarqube-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-extentions-pvc
spec:
  storageClassName: sonarqube-extentions
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec: 
      containers:
        - name: h2o-wave-container
          image: borisdundakovwebapp.azurecr.io/h2o-wave-app:v2
          ports:
            - containerPort: 10101
          command:
            - /bin/bash
            - -c
            - |
              cd ai_app/
              wave run app.py

        - name: sonarqube-container 

          image: sonarqube
          ports:
            - containerPort: 9000

        - name: prometheus-container
          image: prom/prometheus
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          
          volumeMounts:
            - name: prometheus-storage
              mountPath: /etc/prometheus/

          ports:
            - containerPort: 9090
          

      volumes:
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: sonarqube-data-pvc
        
        - name: sonarqube-extentions
          persistentVolumeClaim:
            claimName: sonarqube-extentions-pvc
        
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: prometheus-pvc
          
---

apiVersion: v1
kind: Service
metadata:
  name: port-balancer
spec:
  type: LoadBalancer # Exposes public IP of the application
  ports:
    - name: h2o-wave-port
      port: 10101
      targetPort: 10101
    - name: sonarqube-port
      port: 9000
      targetPort: 9000
    - name: prometheus-port
      port: 9090

  selector:
    app: my-app


---

#Storage account name:           base64
# csa100320028730dfc1       -->   Y3NhMTAwMzIwMDI4NzMwZGZjMQ==

#Storage access key:        -->   WmwwSkh5WDQ5c1dGamd6K3JZZXBSZ2FBdWk2c3YwcUR3UjBjNG5Pd1hXV0JXQ1EzTCtjRjJpdnpzU3B3Z01tQjU4YjRQeVEvZ0pyNStBU3RlUjUvL1E9PQ==
#Zl0JHyX49sWFjgz+rYepRgaAui6sv0qDwR0c4nOwXWWBWCQ3L+cF2ivzsSpwgMmB58b4PyQ/gJr5+ASteR5//Q==