apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: h2o-wave-container
          image: borisdundakov/wave-heroku:0.1.1 # TOOD --> Update this with Azure Container Registry
          ports:
            - containerPort: 10101
          command:
            - /bin/bash
            - -c
            - |
              cd ai_app/
              wave run app.py
        
        
        - name: sonarqube-container # this is where the analysis made by sonaqrube will be viewed
          image: sonarqube
          ports:
            - containerPort: 9000

---

apiVersion: v1
kind: Service
metadata:
  name: port-balancer
spec:
  type: LoadBalancer
  ports:
    - name: h2o-wave-port
      port: 10101
      targetPort: 10101
    - name: sonarqube-port
      port: 9000
      targetPort: 9000
  selector:
    app: my-app
