apiVersion: v1
kind: Namespace
metadata:
    name: waveapp-namespace
spec:
    finalizers:
      - kubernetes


---
# Persistent volume claim to remember Sonarqube setup
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-extensions
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: h2o-wave-container
          image: borisdundakovwebapp.azurecr.io/h2o-wave-app:v2
          ports:
            - containerPort: 10101
          command:
            - /bin/bash
            - -c
            - |
              cd ai_app/
              wave run app.py
        
        
        - name: sonarqube-container # this is where the analysis made by sonaqrube will be viewed
        # TODO --> Add secrets to log into the container and automize repository analysis
        # Set up Automated Static Code Analyze with CI/CD pipeline
          image: sonarqube
          ports:
            - containerPort: 9000
          
          # env:
          #   - name: SONARQUBE_JDBC_URL
          #     value: jdbc:h2:tcp://20.19.106.155:9092/sonar
          #   - name: SONARQUBE_JDBC_USERNAME
          #     value: username
          #   - name: SONARQUBE_JDBC_PASSWORD
          #     value: password
          
          volumeMounts:
            - name: sonarqube-data
              mountPath: /opt/sonarqube/data
            - name: sonarqube-extensions
              mountPath: /opt/sonarqube/extensions
      
      volumes:
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: sonarqube-data
        - name: sonarqube-extensions
          persistentVolumeClaim:
            claimName: sonarqube-extensions
  
---

apiVersion: v1
kind: Service
metadata:
  name: port-balancer
spec:
  type: LoadBalancer # Exposes public IP of the application
  ports:
    - name: h2o-wave-port
      port: 10101
      targetPort: 10101
    - name: sonarqube-port
      port: 9000
      targetPort: 9000
  selector:
    app: my-app


# ---

# apiVersion: v1
# kind: Pod
# metadata:
#   name: sonarqube-scanner
# spec:
#   containers:
#   - name: sonar-scanner
#     image: sonarsource/sonar-scanner-cli:latest
#     command:
#     - "/bin/sh"
#     - "-c"
#     - "sonar-scanner \
#       -Dsonar.projectKey=wave-heroku \
#       -Dsonar.sources=. \
#       -Dsonar.host.url=http://sonarqube:9000 \ 
#       -Dsonar.login=my-sonarqube-token"


#   restartPolicy: Never