apiVersion: v1
kind: Namespace
metadata:
    name: waveapp-namespace
spec:
    finalizers:
      - kubernetes

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: h2o-wave-container
          # $CONTAINER_REG_NAME.azurecr.io/$IMAGE_NAME:v1
          # borisdundakov/wave-heroku:0.1.1
          image: borisdundakovwebapp.azurecr.io/h2o-wave-app:v2 # TOOD --> Update this with Azure Container Registry
          ports:
            - containerPort: 10101
          command:
            - /bin/bash
            - -c
            - |
              cd ai_app/
              wave run app.py
        
        
        - name: sonarqube-container # this is where the analysis made by sonaqrube will be viewed
        # TODO --> Add secrets to log into the container and automize repository analysis
        # Set up Automated Static Code Analyze with CI/CD pipeline
          image: sonarqube
          ports:
            - containerPort: 9000

---

apiVersion: v1
kind: Service
metadata:
  name: port-balancer
spec:
  type: LoadBalancer # Exposes public IP of the application
  ports:
    - name: h2o-wave-port
      port: 10101
      targetPort: 10101
    - name: sonarqube-port
      port: 9000
      targetPort: 9000
  selector:
    app: my-app
