apiVersion: v1
kind: Namespace
metadata:
    name: waveapp-namespace
spec:
    finalizers:
      - kubernetes


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-data-pv
  labels:
    type: local
spec:
  storageClassName: sonaqrube-data
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"



---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-extentions-pv
  labels:
    type: local
spec:
  storageClassName: sonarqube-extentions
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"


---
# Persistent volume claim to remember Sonarqube setup
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-data-pvc
spec:
  storageClassName: sonaqrube-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-extentions-pvc
spec:
  storageClassName: sonarqube-extentions
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec: 
      containers:
        - name: h2o-wave-container
          image: borisdundakovwebapp.azurecr.io/h2o-wave-app:v2
          ports:
            - containerPort: 10101
          command:
            - /bin/bash
            - -c
            - |
              cd ai_app/
              wave run app.py

        
        
        - name: sonarqube-container # this is where the analysis made by sonaqrube will be viewed
        # TODO --> Add secrets to log into the container and automize repository analysis
        # Set up Automated Static Code Analyze with CI/CD pipeline
          image: borisdundakovwebapp.azurecr.io/sonarqube-with-prometheus:v3
          ports:
            - containerPort: 9000
          
          # env:
          #   - name: SONARQUBE_JDBC_URL
          #     value: jdbc:h2:tcp://20.19.106.155:9092/sonar
          #   - name: SONARQUBE_JDBC_USERNAME
          #     value: username
          #   - name: SONARQUBE_JDBC_PASSWORD
          #     value: password
          
          # Here is where the issue lies!
          # volumeMounts:
          #   - name: sonarqube-data
          #     mountPath: /opt/sonarqube/data
          #   - name: sonarqube-extentions
          #     mountPath: /opt/sonarqube/extentions
      
      volumes:
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: sonarqube-data-pvc
        - name: sonarqube-extentions
          persistentVolumeClaim:
            claimName: sonarqube-extentions-pvc
  
---

apiVersion: v1
kind: Service
metadata:
  name: port-balancer
spec:
  type: LoadBalancer # Exposes public IP of the application
  ports:
    - name: h2o-wave-port
      port: 10101
      targetPort: 10101
    - name: sonarqube-port
      port: 9000
      targetPort: 9000
  selector:
    app: my-app


# ---

# apiVersion: v1
# kind: Pod
# metadata:
#   name: sonarqube-scanner
# spec:
#   containers:
#   - name: sonar-scanner
#     image: sonarsource/sonar-scanner-cli:latest
#     command:
#     - "/bin/sh"
#     - "-c"
#     - "sonar-scanner \
#       -Dsonar.projectKey=BorisDundakov-FinalProject \
#       -Dsonar.sources=. \
#       -Dsonar.host.url=http://sonarqube:9000 \ 
#       -Dsonar.login=sqp_7e37065248c5e40ef0098209598895d24166b4ff"


#   restartPolicy: Never