name: actions-exp-v4

on:
  push:
  workflow_dispatch:

jobs:
  github-actions-exporter:
    runs-on: ubuntu-latest
    container:
      image: prom/github-actions-exporter:v0.9.0
      options: --net host
    steps:
      - name: Setup environment
        uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATA_SOURCE: '{"owners": ["bosch-ecs-career-camp"], "repositories": ["BorisDundakov-FinalProject"]}'
      - name: Run GitHub Actions Exporter
        run: docker run -d --name github-actions-exporter -e GITHUB_TOKEN=$GITHUB_TOKEN -e DATA_SOURCE=$DATA_SOURCE -p 9111:9111 prom/github-actions-exporter:v0.9.0
