name: GitHub Actions Exporter

on:
  workflow_dispatch:

jobs:
  github-actions-exporter:
    runs-on: self-hosted
    
    #image: quay.io/prometheus-community/github-exporter:v0.17.0
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATA_SOURCE: '{"owners": ["bosch-ecs-career-camp"], "repositories": ["BorisDundakov-FinalProject"]}'

      - name: Run exporter
        run: |
          docker run \
            --rm \
            -e DATA_SOURCE="$DATA_SOURCE" \
            -e GITHUB_TOKEN="$GITHUB_TOKEN" \
            -p 9999:9999 \
            spendeskplatform/github-actions-exporter:v1.8.1