name: Actions-exporter job

on:
  push:
  workflow_dispatch:
    
jobs:
  build:
    name: Run github-actions-exporter
    runs-on: self-hosted
    steps:
      
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          repository: Spendesk/github-actions-exporter
          path: github-actions-exporter
      
      - name: Build GitHub Actions Exporter Docker image
        run: |
          cd github-actions-exporter
          docker build -t spendeskplatform/github-actions-exporter:latest .
      
      - name: Run GitHub Actions Exporter
        run: |
          docker run -d \
            --name github-actions-exporter-unique-3 \
            -p 9999:9999 \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -e GITHUB_REPOSITORY=${{ github.event.repository.full_name }} \
            spendeskplatform/github-actions-exporter:latest




#-e GITHUB_REPOSITORY=${{ github.repository }} \
            
