name: Actions-exporter job

on:
  push:
  workflow_dispatch:
    
jobs:
  build:
    name: Run github-actions-exporter
    runs-on: self-hosted
    steps:
      
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          repository: Spendesk/github-actions-exporter
          path: github-actions-exporter
      
      - name: Build GitHub Actions Exporter Docker image
        run: |
          cd github-actions-exporter
          docker build -t spendeskplatform/github-actions-exporter:latest .
      
      
      #TODO: Delete prevous containers to avoid name duplication
      - name: Run GitHub Actions Exporter
        run: |
          docker run -d \
            --name github-actions-exporter-unique-27 \
            -p 9999:9999 \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -e GITHUB_REPOSITORY=${{ github.event.repository.full_name }} \
            spendeskplatform/github-actions-exporter:v1.8.1
    
      - name: Pointless echo
        run: |
          echo ${{ github.event.repository.full_name }}
      
      - name: Expose workflow run status
        run: |
            echo "github_workflow_run_status $(echo ${{ job.status }} | tr '[:upper:]' '[:lower:]') $(date +%s)" | \
              docker run --rm -i --network=host --entrypoint=/bin/sh -e "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" \
              spendeskplatform/github-actions-exporter:latest -c 'echo "$0" | curl --data-binary @- http://localhost:9999/metrics/job/github_workflow_run_status/instance/$GITHUB_REPOSITORY' 


#-e GITHUB_REPOSITORY=${{ github.repository }} \
            
