name: Automatic deployment production
on:
  workflow_dispatch:
  workflow_run:
    workflows: [" Sonarqube and H2o images build prod"]
    types:
      - "completed"

jobs:
  run-deployment:
     runs-on: self-hosted

     steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
      
      - name: run deployment yml file
        run: |
              kubectl apply -f deployment/aks-deployment.yml
        
      
      - name: get public IP 
        run: |
              kubectl get services
