name: Automatic deployment test
on: 
  workflow_run:
    workflows: [" Sonarqube and H2o images build test"]
    types:
      - "completed"

jobs:
  run-deployment:
     runs-on: self-hosted

     steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
      
      - name: run deployment yml file
        run: |
              kubectl apply -f deployment/aks-deployment-test.yml
        
      
      - name: get public IP 
        run: |
              kubectl get services
