name: Run Azure Login with OIDC
on: workflow_dispatch

jobs: 

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        #environment: 'AzureStack'

    - run: |
        az group list 
