name: Create AKS Cluster
on: workflow_dispatch

env:
  PUBLIC_KEY: ${{ secrets.AZURE_PUB_KEY }}


jobs:
  create-aks:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
      
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 

      - name: Execute bash cluster-creation script
        run: |
              pwd
              ls -a
              chmod +x azure-scripts/cluster-creation.sh 
              ./azure-scripts/cluster-creation.sh PUBLIC_KEY
        
  # deploy-pods:
  #   runs-on: ubuntu-22.04
    
