name: Run deployment
on: workflow_dispatch

jobs:
  run-deployment:
     runs-on: self-hosted

     steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
      
      - name: run deployment yml file
        run: |
              kubectl apply -f deployment/aks-deployment-test.yml
        
      
      - name: get public IP 
        run: |
              kubectl get services
